name: ChicknTender
description: Making deciding your next meal easier.
version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  rxdart: 0.20.0
  url_launcher: 4.0.3
  units: 0.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  uri: ^0.11.3
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

